import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles, Target, BookOpen, Pin, Lightbulb, Save } from 'lucide-react';
import { useUser } from '../../context/userContext';
import Login from '../Auth/Login';
import SignUp from '../Auth/SignUp';

const LandingPage = () => {
  const navigate = useNavigate();
  const { isAuthenticated } = useUser();
  const [showLogin, setShowLogin] = useState(false);
  const [showSignup, setShowSignup] = useState(false);

  const handleGetStarted = () => {
    if (isAuthenticated) {
      navigate('/dashboard');
    } else {
      setShowLogin(true);
    }
  };

  const features = [
    {
      icon: <Target className="w-8 h-8" />,
      title: 'Tailored Just for You',
      description:
        'Get interview questions and model answers based on your role, experience, and specific focus areas — no generic practice here.',
    },
    {
      icon: <BookOpen className="w-8 h-8" />,
      title: 'Learn at Your Own Pace',
      description:
        'Expand answers only when you\'re ready. Dive deeper into any concept instantly with AI-powered detailed explanations.',
    },
    {
      icon: <Pin className="w-8 h-8" />,
      title: 'Capture Your Insights',
      description:
        'Add personal notes to any question and pin important ones to the top — making your learning more organized and impactful.',
    },
    {
      icon: <Lightbulb className="w-8 h-8" />,
      title: 'Understand the "Why" Behind Answers',
      description:
        'Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.',
    },
    {
      icon: <Save className="w-8 h-8" />,
      title: 'Save, Organize, and Revisit',
      description:
        'Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.',
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-orange-50">
      {/* Navbar */}
      <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-orange-600" />
            <h1 className="text-2xl font-bold text-gray-900">Interview Prep AI</h1>
          </div>
          <button
            onClick={() => isAuthenticated ? navigate('/dashboard') : setShowLogin(true)}
            className="px-6 py-2.5 bg-orange-600 hover:bg-orange-700 text-white font-medium rounded-full transition-all duration-300 hover:shadow-lg hover:scale-105"
          >
            {isAuthenticated ? 'Dashboard' : 'Login / Sign Up'}
          </button>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-6 py-20">
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-orange-100 text-orange-700 rounded-full text-sm font-medium mb-6">
            <Sparkles className="w-4 h-4" />
            AI Powered
          </div>
          <h2 className="text-6xl font-bold text-gray-900 mb-6">
            Ace Interviews with
            <br />
            <span className="text-orange-600">AI-Powered</span> Learning
          </h2>
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto leading-relaxed">
            Get role-specific questions, expand answers when you need them, dive deeper into concepts, and organize everything your way. From preparation to mastery — your ultimate interview toolkit is here.
          </p>
          <button
            onClick={handleGetStarted}
            className="px-8 py-4 bg-gray-900 hover:bg-gray-800 text-white font-semibold rounded-full text-lg transition-all duration-300 hover:shadow-2xl hover:scale-105"
          >
            Get Started
          </button>
        </div>

        {/* Screenshot Preview */}
        <div className="relative">
          <div className="absolute inset-0 bg-gradient-to-r from-orange-400 to-orange-600 rounded-3xl blur-3xl opacity-20"></div>
          <div className="relative bg-white rounded-2xl shadow-2xl border border-gray-200 overflow-hidden">
            <div className="bg-gradient-to-br from-orange-50 to-white p-12">
              <div className="bg-white rounded-xl shadow-lg border border-gray-200 p-8">
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-12 h-12 rounded-full bg-orange-100 flex items-center justify-center">
                    <span className="text-xl font-bold text-orange-600">FD</span>
                  </div>
                  <div>
                    <h3 className="font-bold text-gray-900">Frontend Developer</h3>
                    <p className="text-sm text-gray-600">React.js, DOM manipulation, CSS Flexbox</p>
                  </div>
                </div>
                <div className="space-y-4">
                  <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
                    <p className="font-medium text-gray-900 mb-2">What is JSX? Explain its role in React.</p>
                    <button className="text-sm text-orange-600 font-medium">Learn More →</button>
                  </div>
                  <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
                    <p className="font-medium text-gray-900 mb-2">Explain the concept of event handling in React.</p>
                    <button className="text-sm text-orange-600 font-medium">Learn More →</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="max-w-7xl mx-auto px-6 py-20">
        <h3 className="text-4xl font-bold text-center text-gray-900 mb-16">
          Features That Make You Shine
        </h3>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <div
              key={index}
              className="p-8 bg-white rounded-2xl shadow-lg border border-gray-100 hover:shadow-2xl transition-all duration-300 hover:-translate-y-1"
            >
              <div className="w-16 h-16 bg-orange-100 rounded-xl flex items-center justify-center text-orange-600 mb-6">
                {feature.icon}
              </div>
              <h4 className="text-xl font-bold text-gray-900 mb-4">{feature.title}</h4>
              <p className="text-gray-600 leading-relaxed">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="max-w-7xl mx-auto px-6 py-20">
        <div className="bg-gradient-to-br from-orange-600 to-orange-700 rounded-3xl p-16 text-center shadow-2xl">
          <h3 className="text-4xl font-bold text-white mb-6">
            Ready to Ace Your Next Interview?
          </h3>
          <p className="text-xl text-orange-100 mb-8 max-w-2xl mx-auto">
            Join thousands of developers preparing smarter with AI-powered interview prep
          </p>
          <button
            onClick={handleGetStarted}
            className="px-8 py-4 bg-white text-orange-600 font-semibold rounded-full text-lg hover:shadow-2xl transition-all duration-300 hover:scale-105"
          >
            Start Learning Now
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-200 py-8">
        <div className="max-w-7xl mx-auto px-6 text-center text-gray-600">
          <p>© 2025 Interview Prep AI. Built with ❤️ for developers.</p>
        </div>
      </footer>

      {/* Modals */}
      {showLogin && <Login onClose={() => setShowLogin(false)} onSwitchToSignup={() => {
        setShowLogin(false);
        setShowSignup(true);
      }} />}
      {showSignup && <SignUp onClose={() => setShowSignup(false)} onSwitchToLogin={() => {
        setShowSignup(false);
        setShowLogin(true);
      }} />}
    </div>
  );
};

export default LandingPage;
